### ISSUE TITLE
Clean up directory structure, is too messy

### ISSUE THREAD

**Issue by khufkens** [khufkens/daymetpy#1]

**Comment by ghost** [comment]
How so?  The directory structure looks fairly standard to me.

**Comment by khufkens** [comment]
I'm not a fan of the ipython notebooks, and convoluted structures. I think they complicate things, while the use should be advertised on the README page - so you can grasp the use of the function at a glance (on the landing page - rather than having to open a separate document). I realized that my github page is as much a resume / CV as anything else I do. Hence me being rather up tight about this. I hope you understand. This is my bread and butter. How organized everything is reflects on job prospects.

**Comment by khufkens** [comment]
This is a personal preference more than anything else. I'll put some time into writing a tutorial page later on. But as I said this matters job wise.

**Comment by khufkens** [comment]
I'm aiming towards a uniform structure and documentation scheme similar to https://github.com/khufkens/daymetr

**Comment by ghost** [comment]
Sounds good.  It's definitely your package, so feel free to manipulate it however you would like.  Turns out there are a couple of other more widely used python packages that have this same functionality, so it doesn't make too much difference to me.

Updating the readme to provide a comprehensive intro only makes sense.  But IMHO the use of jupyter notebooks for examples is fairly common in the Python community.  The fact that they render on Github is a fantastic way to communicate functionality.  I left the .py version in as well for folks that aren't using jupyter.

--Colin

**Comment by khufkens** [comment]
I see the value of notebook, but it's just one click too far away. I'll make a similar README, keep the notebook but fold everything into one directory (there only a few files anyway).

**Comment by khufkens** [comment]
kept most of the structure, so I don't potentially break the pip install.
